attest: Make sure trees are sorted. (#132)
Git trees apparently need to be sorted by name.

Fixes error:

```
remote: error: object 7c8ce5a1d674a439b75abca064c24bfe1aaa6767: treeNotSorted: not properly sorted
remote: fatal: fsck error in packed object
error: remote unpack failed: index-pack abnormal exit
```

Signed-off-by: Billy Lynch <billy@chainguard.dev>